import 'package:bloc/bloc.dart';
import 'package:flutter/widgets.dart';

part 'filters_state.dart';

class FiltersCubit extends Cubit<FiltersState> {
  FiltersCubit()
      : super(FiltersState(
            checkboxSortByDistanceValue: false,
            checkboxFavoritesValue: false,
            checkboxUserPointValue: false,
            checkboxNewGuestValue: false,
            checkboxRestaurantPayment: false,
            checkboxOnlinePayment: false,
            checkboxChicken: false,
            checkboxCoffe: false,
            checkboxDessert: false,
            checkboxDrinks: false,
            checkboxHamburger: false,
            checkboxMainCourse: false,
            checkboxPizza: false,
            checkboxSelectAll: false,
            checkboxVegan: false,
            checkboxMotorCourier: false,
            checkboxTakeOutPackage: false,
            textFieldMaxValue: TextEditingController(),
            textFieldMinValue: TextEditingController(),
            maxValue: 500,
            minValue: 10,));

  void setIsCheckboxSortByDistanceValue(bool checkboxSortByDistanceValue) => emit(FiltersState(
          checkboxSortByDistanceValue: state.checkboxSortByDistanceValue =
              checkboxSortByDistanceValue,
          checkboxFavoritesValue: state.checkboxFavoritesValue,
          checkboxNewGuestValue: state.checkboxNewGuestValue,
          checkboxUserPointValue: state.checkboxUserPointValue,
          checkboxRestaurantPayment: state.checkboxRestaurantPayment,
          checkboxOnlinePayment: state.checkboxOnlinePayment,
          checkboxChicken: state.checkboxChicken,
          checkboxCoffe: state.checkboxCoffe,
          checkboxDessert: state.checkboxDessert,
          checkboxDrinks: state.checkboxDrinks,
          checkboxHamburger: state.checkboxHamburger,
          checkboxMainCourse: state.checkboxMainCourse,
          checkboxPizza: state.checkboxPizza,
          checkboxSelectAll: state.checkboxSelectAll,
          checkboxVegan: state.checkboxVegan,
          checkboxMotorCourier: state.checkboxMotorCourier,
          checkboxTakeOutPackage: state.checkboxTakeOutPackage,
          textFieldMaxValue: state.textFieldMaxValue,
          textFieldMinValue: state.textFieldMinValue,
          maxValue: state.maxValue,
          minValue: state.minValue,
          ));
  void setIsCheckboxFavoritesValue(bool checkboxFavoritesValue) => emit(FiltersState(
          checkboxFavoritesValue: state.checkboxFavoritesValue =
              checkboxFavoritesValue,
          checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
          checkboxNewGuestValue: state.checkboxNewGuestValue,
          checkboxUserPointValue: state.checkboxUserPointValue,
          checkboxRestaurantPayment: state.checkboxRestaurantPayment,
          checkboxOnlinePayment: state.checkboxOnlinePayment,
          checkboxChicken: state.checkboxChicken,
          checkboxCoffe: state.checkboxCoffe,
          checkboxDessert: state.checkboxDessert,
          checkboxDrinks: state.checkboxDrinks,
          checkboxHamburger: state.checkboxHamburger,
          checkboxMainCourse: state.checkboxMainCourse,
          checkboxPizza: state.checkboxPizza,
          checkboxSelectAll: state.checkboxSelectAll,
          checkboxVegan: state.checkboxVegan,
          checkboxMotorCourier: state.checkboxMotorCourier,
          checkboxTakeOutPackage: state.checkboxTakeOutPackage,
          textFieldMaxValue: state.textFieldMaxValue,
          textFieldMinValue: state.textFieldMinValue,
          maxValue: state.maxValue,
          minValue: state.minValue));
  void setIsCheckboxUserPointValue(bool checkboxUserPointValue) => emit(FiltersState(
          checkboxUserPointValue: state.checkboxUserPointValue =
              checkboxUserPointValue,
          checkboxFavoritesValue: state.checkboxFavoritesValue,
          checkboxNewGuestValue: state.checkboxNewGuestValue,
          checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
          checkboxRestaurantPayment: state.checkboxRestaurantPayment,
          checkboxOnlinePayment: state.checkboxOnlinePayment,
          checkboxChicken: state.checkboxChicken,
          checkboxCoffe: state.checkboxCoffe,
          checkboxDessert: state.checkboxDessert,
          checkboxDrinks: state.checkboxDrinks,
          checkboxHamburger: state.checkboxHamburger,
          checkboxMainCourse: state.checkboxMainCourse,
          checkboxPizza: state.checkboxPizza,
          checkboxSelectAll: state.checkboxSelectAll,
          checkboxVegan: state.checkboxVegan,
          checkboxMotorCourier: state.checkboxMotorCourier,
          checkboxTakeOutPackage: state.checkboxTakeOutPackage,
          textFieldMaxValue: state.textFieldMaxValue,
          textFieldMinValue: state.textFieldMinValue,
          maxValue: state.maxValue,
          minValue: state.minValue));
  void setIsCheckboxNewGuestValue(bool checkboxNewGuestValue) => emit(FiltersState(
          checkboxNewGuestValue: state.checkboxNewGuestValue =
              checkboxNewGuestValue,
          checkboxFavoritesValue: state.checkboxFavoritesValue,
          checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
          checkboxUserPointValue: state.checkboxUserPointValue,
          checkboxRestaurantPayment: state.checkboxRestaurantPayment,
          checkboxOnlinePayment: state.checkboxOnlinePayment,
          checkboxChicken: state.checkboxChicken,
          checkboxCoffe: state.checkboxCoffe,
          checkboxDessert: state.checkboxDessert,
          checkboxDrinks: state.checkboxDrinks,
          checkboxHamburger: state.checkboxHamburger,
          checkboxMainCourse: state.checkboxMainCourse,
          checkboxPizza: state.checkboxPizza,
          checkboxSelectAll: state.checkboxSelectAll,
          checkboxVegan: state.checkboxVegan,
          checkboxMotorCourier: state.checkboxMotorCourier,
          checkboxTakeOutPackage: state.checkboxTakeOutPackage,
          textFieldMaxValue: state.textFieldMaxValue,
          textFieldMinValue: state.textFieldMinValue,
          maxValue: state.maxValue,
          minValue: state.minValue));

  void setIsCheckboxPaymentOnline(bool checkboxOnlinePayment) => emit(FiltersState(
          checkboxOnlinePayment: state.checkboxOnlinePayment =
              checkboxOnlinePayment,
          checkboxRestaurantPayment: state.checkboxRestaurantPayment,
          checkboxFavoritesValue: state.checkboxFavoritesValue,
          checkboxNewGuestValue: state.checkboxNewGuestValue,
          checkboxUserPointValue: state.checkboxUserPointValue,
          checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
          checkboxChicken: state.checkboxChicken,
          checkboxCoffe: state.checkboxCoffe,
          checkboxDessert: state.checkboxDessert,
          checkboxDrinks: state.checkboxDrinks,
          checkboxHamburger: state.checkboxHamburger,
          checkboxMainCourse: state.checkboxMainCourse,
          checkboxPizza: state.checkboxPizza,
          checkboxSelectAll: state.checkboxSelectAll,
          checkboxVegan: state.checkboxVegan,
          checkboxMotorCourier: state.checkboxMotorCourier,
          checkboxTakeOutPackage: state.checkboxTakeOutPackage,
          textFieldMaxValue: state.textFieldMaxValue,
          textFieldMinValue: state.textFieldMinValue,
          maxValue: state.maxValue,
          minValue: state.minValue
          ));
  void setIsCheckboxPaymentRestaurant(bool checkboxRestaurantPayment) => emit(FiltersState(
          checkboxRestaurantPayment: state.checkboxRestaurantPayment =
              checkboxRestaurantPayment,
          checkboxOnlinePayment: state.checkboxOnlinePayment,
          checkboxFavoritesValue: state.checkboxFavoritesValue,
          checkboxNewGuestValue: state.checkboxNewGuestValue,
          checkboxUserPointValue: state.checkboxUserPointValue,
          checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
          checkboxChicken: state.checkboxChicken,
          checkboxCoffe: state.checkboxCoffe,
          checkboxDessert: state.checkboxDessert,
          checkboxDrinks: state.checkboxDrinks,
          checkboxHamburger: state.checkboxHamburger,
          checkboxMainCourse: state.checkboxMainCourse,
          checkboxPizza: state.checkboxPizza,
          checkboxSelectAll: state.checkboxSelectAll,
          checkboxVegan: state.checkboxVegan,
          checkboxMotorCourier: state.checkboxMotorCourier,
          checkboxTakeOutPackage: state.checkboxTakeOutPackage,
          textFieldMaxValue: state.textFieldMaxValue,
          textFieldMinValue: state.textFieldMinValue,
          maxValue: state.maxValue,
          minValue: state.minValue
          ));

  void setIsCheckboxSelectAll(bool checkboxSelectAll) => emit(FiltersState(
      checkboxSelectAll: state.checkboxSelectAll = checkboxSelectAll,
      checkboxOnlinePayment: state.checkboxOnlinePayment,
      checkboxFavoritesValue: state.checkboxFavoritesValue,
      checkboxNewGuestValue: state.checkboxNewGuestValue,
      checkboxUserPointValue: state.checkboxUserPointValue,
      checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
      checkboxChicken: state.checkboxChicken,
      checkboxCoffe: state.checkboxCoffe,
      checkboxDessert: state.checkboxDessert,
      checkboxDrinks: state.checkboxDrinks,
      checkboxHamburger: state.checkboxHamburger,
      checkboxMainCourse: state.checkboxMainCourse,
      checkboxPizza: state.checkboxPizza,
      checkboxVegan: state.checkboxVegan,
      checkboxMotorCourier: state.checkboxMotorCourier,
      checkboxTakeOutPackage: state.checkboxTakeOutPackage,
      textFieldMaxValue: state.textFieldMaxValue,
      textFieldMinValue: state.textFieldMinValue,
      maxValue: state.maxValue,
      minValue: state.minValue));
  void setIsCheckboxMainCourse(bool checkboxMainCourse) => emit(FiltersState(
      checkboxMainCourse: state.checkboxMainCourse = checkboxMainCourse,
      checkboxOnlinePayment: state.checkboxOnlinePayment,
      checkboxFavoritesValue: state.checkboxFavoritesValue,
      checkboxNewGuestValue: state.checkboxNewGuestValue,
      checkboxUserPointValue: state.checkboxUserPointValue,
      checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
      checkboxChicken: state.checkboxChicken,
      checkboxCoffe: state.checkboxCoffe,
      checkboxDessert: state.checkboxDessert,
      checkboxDrinks: state.checkboxDrinks,
      checkboxHamburger: state.checkboxHamburger,
      checkboxPizza: state.checkboxPizza,
      checkboxSelectAll: state.checkboxSelectAll,
      checkboxVegan: state.checkboxVegan,
      checkboxMotorCourier: state.checkboxMotorCourier,
      checkboxTakeOutPackage: state.checkboxTakeOutPackage,
      textFieldMaxValue: state.textFieldMaxValue,
      textFieldMinValue: state.textFieldMinValue,
      maxValue: state.maxValue,
      minValue: state.minValue));
  void setIsCheckboxDrinks(bool checkboxDrinks) => emit(FiltersState(
      checkboxDrinks: state.checkboxDrinks = checkboxDrinks,
      checkboxOnlinePayment: state.checkboxOnlinePayment,
      checkboxFavoritesValue: state.checkboxFavoritesValue,
      checkboxNewGuestValue: state.checkboxNewGuestValue,
      checkboxUserPointValue: state.checkboxUserPointValue,
      checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
      checkboxChicken: state.checkboxChicken,
      checkboxCoffe: state.checkboxCoffe,
      checkboxDessert: state.checkboxDessert,
      checkboxHamburger: state.checkboxHamburger,
      checkboxPizza: state.checkboxPizza,
      checkboxSelectAll: state.checkboxSelectAll,
      checkboxVegan: state.checkboxVegan,
      checkboxMainCourse: state.checkboxMainCourse,
      checkboxRestaurantPayment: state.checkboxRestaurantPayment,
      checkboxMotorCourier: state.checkboxMotorCourier,
      checkboxTakeOutPackage: state.checkboxTakeOutPackage,
      textFieldMaxValue: state.textFieldMaxValue,
      textFieldMinValue: state.textFieldMinValue,
      maxValue: state.maxValue,
      minValue: state.minValue));
  void setIsCheckboxVegan(bool checkboxVegan) => emit(FiltersState(
      checkboxVegan: state.checkboxVegan = checkboxVegan,
      checkboxOnlinePayment: state.checkboxOnlinePayment,
      checkboxFavoritesValue: state.checkboxFavoritesValue,
      checkboxNewGuestValue: state.checkboxNewGuestValue,
      checkboxUserPointValue: state.checkboxUserPointValue,
      checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
      checkboxChicken: state.checkboxChicken,
      checkboxCoffe: state.checkboxCoffe,
      checkboxDessert: state.checkboxDessert,
      checkboxHamburger: state.checkboxHamburger,
      checkboxPizza: state.checkboxPizza,
      checkboxSelectAll: state.checkboxSelectAll,
      checkboxDrinks: state.checkboxDrinks,
      checkboxMainCourse: state.checkboxMainCourse,
      checkboxRestaurantPayment: state.checkboxRestaurantPayment,
      checkboxMotorCourier: state.checkboxMotorCourier,
      checkboxTakeOutPackage: state.checkboxTakeOutPackage,
      textFieldMaxValue: state.textFieldMaxValue,
      textFieldMinValue: state.textFieldMinValue,
      maxValue: state.maxValue,
      minValue: state.minValue));
  void setIsCheckboxHamburger(bool checkboxHamburger) => emit(FiltersState(
      checkboxHamburger: state.checkboxHamburger = checkboxHamburger,
      checkboxOnlinePayment: state.checkboxOnlinePayment,
      checkboxFavoritesValue: state.checkboxFavoritesValue,
      checkboxNewGuestValue: state.checkboxNewGuestValue,
      checkboxUserPointValue: state.checkboxUserPointValue,
      checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
      checkboxChicken: state.checkboxChicken,
      checkboxCoffe: state.checkboxCoffe,
      checkboxDessert: state.checkboxDessert,
      checkboxPizza: state.checkboxPizza,
      checkboxSelectAll: state.checkboxSelectAll,
      checkboxDrinks: state.checkboxDrinks,
      checkboxMainCourse: state.checkboxMainCourse,
      checkboxRestaurantPayment: state.checkboxRestaurantPayment,
      checkboxVegan: state.checkboxVegan,
      checkboxMotorCourier: state.checkboxMotorCourier,
      checkboxTakeOutPackage: state.checkboxTakeOutPackage,
      textFieldMaxValue: state.textFieldMaxValue,
      textFieldMinValue: state.textFieldMinValue,
      maxValue: state.maxValue,
      minValue: state.minValue));
  void setIsCheckboxDessert(bool checkboxDessert) => emit(FiltersState(
      checkboxDessert: state.checkboxDessert = checkboxDessert,
      checkboxOnlinePayment: state.checkboxOnlinePayment,
      checkboxFavoritesValue: state.checkboxFavoritesValue,
      checkboxNewGuestValue: state.checkboxNewGuestValue,
      checkboxUserPointValue: state.checkboxUserPointValue,
      checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
      checkboxChicken: state.checkboxChicken,
      checkboxCoffe: state.checkboxCoffe,
      checkboxPizza: state.checkboxPizza,
      checkboxSelectAll: state.checkboxSelectAll,
      checkboxDrinks: state.checkboxDrinks,
      checkboxHamburger: state.checkboxHamburger,
      checkboxMainCourse: state.checkboxMainCourse,
      checkboxRestaurantPayment: state.checkboxRestaurantPayment,
      checkboxVegan: state.checkboxVegan,
      checkboxMotorCourier: state.checkboxMotorCourier,
      checkboxTakeOutPackage: state.checkboxTakeOutPackage,
      textFieldMaxValue: state.textFieldMaxValue,
      textFieldMinValue: state.textFieldMinValue,
      maxValue: state.maxValue,
      minValue: state.minValue));
  void setIsCheckboxPizza(bool checkboxPizza) => emit(FiltersState(
      checkboxPizza: state.checkboxPizza = checkboxPizza,
      checkboxOnlinePayment: state.checkboxOnlinePayment,
      checkboxFavoritesValue: state.checkboxFavoritesValue,
      checkboxNewGuestValue: state.checkboxNewGuestValue,
      checkboxUserPointValue: state.checkboxUserPointValue,
      checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
      checkboxChicken: state.checkboxChicken,
      checkboxCoffe: state.checkboxCoffe,
      checkboxSelectAll: state.checkboxSelectAll,
      checkboxDessert: state.checkboxDessert,
      checkboxDrinks: state.checkboxDrinks,
      checkboxHamburger: state.checkboxHamburger,
      checkboxMainCourse: state.checkboxMainCourse,
      checkboxRestaurantPayment: state.checkboxRestaurantPayment,
      checkboxVegan: state.checkboxVegan,
      checkboxMotorCourier: state.checkboxMotorCourier,
      checkboxTakeOutPackage: state.checkboxTakeOutPackage,
      textFieldMaxValue: state.textFieldMaxValue,
      textFieldMinValue: state.textFieldMinValue,
      maxValue: state.maxValue,
      minValue: state.minValue));
  void setIsCheckboxChicken(bool checkboxChicken) => emit(FiltersState(
      checkboxChicken: state.checkboxChicken = checkboxChicken,
      checkboxOnlinePayment: state.checkboxOnlinePayment,
      checkboxFavoritesValue: state.checkboxFavoritesValue,
      checkboxNewGuestValue: state.checkboxNewGuestValue,
      checkboxUserPointValue: state.checkboxUserPointValue,
      checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
      checkboxCoffe: state.checkboxCoffe,
      checkboxSelectAll: state.checkboxSelectAll,
      checkboxDessert: state.checkboxDessert,
      checkboxDrinks: state.checkboxDrinks,
      checkboxHamburger: state.checkboxHamburger,
      checkboxMainCourse: state.checkboxMainCourse,
      checkboxPizza: state.checkboxPizza,
      checkboxRestaurantPayment: state.checkboxRestaurantPayment,
      checkboxVegan: state.checkboxVegan,
      checkboxMotorCourier: state.checkboxMotorCourier,
      checkboxTakeOutPackage: state.checkboxTakeOutPackage,
      textFieldMaxValue: state.textFieldMaxValue,
      textFieldMinValue: state.textFieldMinValue,
      maxValue: state.maxValue,
      minValue: state.minValue

  ));
  void setIsCheckboxCoffe(bool checkboxCoffe) => emit(FiltersState(
        checkboxCoffe: state.checkboxCoffe = checkboxCoffe,
        checkboxOnlinePayment: state.checkboxOnlinePayment,
        checkboxFavoritesValue: state.checkboxFavoritesValue,
        checkboxNewGuestValue: state.checkboxNewGuestValue,
        checkboxUserPointValue: state.checkboxUserPointValue,
        checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
        checkboxSelectAll: state.checkboxSelectAll,
        checkboxChicken: state.checkboxChicken,
        checkboxDessert: state.checkboxDessert,
        checkboxDrinks: state.checkboxDrinks,
        checkboxHamburger: state.checkboxHamburger,
        checkboxMainCourse: state.checkboxMainCourse,
        checkboxPizza: state.checkboxPizza,
        checkboxRestaurantPayment: state.checkboxRestaurantPayment,
        checkboxVegan: state.checkboxVegan,
        checkboxMotorCourier: state.checkboxMotorCourier,
        checkboxTakeOutPackage: state.checkboxTakeOutPackage,
      textFieldMaxValue: state.textFieldMaxValue,
      textFieldMinValue: state.textFieldMinValue,
      maxValue: state.maxValue,
      minValue: state.minValue
        

      ));

  void setIsCheckboxMotorCourier(bool checkboxMotorCourier) => emit(FiltersState(
      checkboxMotorCourier: state.checkboxMotorCourier = checkboxMotorCourier,
      checkboxOnlinePayment: state.checkboxOnlinePayment,
      checkboxFavoritesValue: state.checkboxFavoritesValue,
      checkboxNewGuestValue: state.checkboxNewGuestValue,
      checkboxUserPointValue: state.checkboxUserPointValue,
      checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
      checkboxSelectAll: state.checkboxSelectAll,
      checkboxChicken: state.checkboxChicken,
      checkboxDessert: state.checkboxDessert,
      checkboxDrinks: state.checkboxDrinks,
      checkboxHamburger: state.checkboxHamburger,
      checkboxMainCourse: state.checkboxMainCourse,
      checkboxPizza: state.checkboxPizza,
      checkboxRestaurantPayment: state.checkboxRestaurantPayment,
      checkboxVegan: state.checkboxVegan,
      checkboxTakeOutPackage: state.checkboxTakeOutPackage,
      checkboxCoffe: state.checkboxCoffe,
      textFieldMaxValue: state.textFieldMaxValue,
      textFieldMinValue: state.textFieldMinValue,
      maxValue: state.maxValue,
      minValue: state.minValue,
      ));
  void setIsCheckboxTakeOutPackage(bool checkboxTakeOutPackage) => emit(FiltersState(
          checkboxTakeOutPackage: state.checkboxTakeOutPackage =
          checkboxTakeOutPackage,
          checkboxOnlinePayment: state.checkboxOnlinePayment,
          checkboxFavoritesValue: state.checkboxFavoritesValue,
          checkboxNewGuestValue: state.checkboxNewGuestValue,
          checkboxUserPointValue: state.checkboxUserPointValue,
          checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
          checkboxSelectAll: state.checkboxSelectAll,
          checkboxChicken: state.checkboxChicken,
          checkboxDessert: state.checkboxDessert,
          checkboxDrinks: state.checkboxDrinks,
          checkboxHamburger: state.checkboxHamburger,
          checkboxMainCourse: state.checkboxMainCourse,
          checkboxPizza: state.checkboxPizza,
          checkboxRestaurantPayment: state.checkboxRestaurantPayment,
          checkboxVegan: state.checkboxVegan,
          checkboxMotorCourier: state.checkboxMotorCourier,
          checkboxCoffe: state.checkboxCoffe,
          textFieldMaxValue: state.textFieldMaxValue,
          textFieldMinValue: state.textFieldMinValue,
          maxValue: state.maxValue,
          minValue: state.minValue,
          
    ));

    void setIsTextFieldMaxValue(TextEditingController textFieldMaxValue) => emit(FiltersState(
          textFieldMaxValue: state.textFieldMaxValue =
              textFieldMaxValue,
          checkboxOnlinePayment: state.checkboxOnlinePayment,
          checkboxFavoritesValue: state.checkboxFavoritesValue,
          checkboxNewGuestValue: state.checkboxNewGuestValue,
          checkboxUserPointValue: state.checkboxUserPointValue,
          checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
          checkboxSelectAll: state.checkboxSelectAll,
          checkboxChicken: state.checkboxChicken,
          checkboxDessert: state.checkboxDessert,
          checkboxDrinks: state.checkboxDrinks,
          checkboxHamburger: state.checkboxHamburger,
          checkboxMainCourse: state.checkboxMainCourse,
          checkboxPizza: state.checkboxPizza,
          checkboxRestaurantPayment: state.checkboxRestaurantPayment,
          checkboxVegan: state.checkboxVegan,
          checkboxMotorCourier: state.checkboxMotorCourier,
          checkboxCoffe: state.checkboxCoffe,
          textFieldMinValue: state.textFieldMinValue,
          maxValue: state.maxValue,
          minValue: state.minValue,
          checkboxTakeOutPackage: state.checkboxTakeOutPackage));
    void setIsTextFieldMinValue(TextEditingController textFieldMinValue) => emit(FiltersState(
      textFieldMinValue: state.textFieldMinValue = textFieldMinValue,
      checkboxOnlinePayment: state.checkboxOnlinePayment,
      checkboxFavoritesValue: state.checkboxFavoritesValue,
      checkboxNewGuestValue: state.checkboxNewGuestValue,
      checkboxUserPointValue: state.checkboxUserPointValue,
      checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
      checkboxSelectAll: state.checkboxSelectAll,
      checkboxChicken: state.checkboxChicken,
      checkboxDessert: state.checkboxDessert,
      checkboxDrinks: state.checkboxDrinks,
      checkboxHamburger: state.checkboxHamburger,
      checkboxMainCourse: state.checkboxMainCourse,
      checkboxPizza: state.checkboxPizza,
      checkboxRestaurantPayment: state.checkboxRestaurantPayment,
      checkboxVegan: state.checkboxVegan,
      checkboxMotorCourier: state.checkboxMotorCourier,
      checkboxCoffe: state.checkboxCoffe,
      maxValue: state.maxValue,
      minValue: state.minValue,
      checkboxTakeOutPackage: state.checkboxTakeOutPackage,
      ));

    void setIsMinValue(int minValue) => emit(FiltersState(
          minValue: state.minValue = minValue.toDouble(),
          checkboxOnlinePayment: state.checkboxOnlinePayment,
          checkboxFavoritesValue: state.checkboxFavoritesValue,
          checkboxNewGuestValue: state.checkboxNewGuestValue,
          checkboxUserPointValue: state.checkboxUserPointValue,
          checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
          checkboxSelectAll: state.checkboxSelectAll,
          checkboxChicken: state.checkboxChicken,
          checkboxDessert: state.checkboxDessert,
          checkboxDrinks: state.checkboxDrinks,
          checkboxHamburger: state.checkboxHamburger,
          checkboxMainCourse: state.checkboxMainCourse,
          checkboxPizza: state.checkboxPizza,
          checkboxRestaurantPayment: state.checkboxRestaurantPayment,
          checkboxVegan: state.checkboxVegan,
          checkboxMotorCourier: state.checkboxMotorCourier,
          checkboxCoffe: state.checkboxCoffe,
          maxValue: state.maxValue,
          checkboxTakeOutPackage: state.checkboxTakeOutPackage
          ));
    void setIsMaxValue(int maxValue) => emit(FiltersState(
        maxValue: state.maxValue = maxValue.toDouble(),
        checkboxOnlinePayment: state.checkboxOnlinePayment,
        checkboxFavoritesValue: state.checkboxFavoritesValue,
        checkboxNewGuestValue: state.checkboxNewGuestValue,
        checkboxUserPointValue: state.checkboxUserPointValue,
        checkboxSortByDistanceValue: state.checkboxSortByDistanceValue,
        checkboxSelectAll: state.checkboxSelectAll,
        checkboxChicken: state.checkboxChicken,
        checkboxDessert: state.checkboxDessert,
        checkboxDrinks: state.checkboxDrinks,
        checkboxHamburger: state.checkboxHamburger,
        checkboxMainCourse: state.checkboxMainCourse,
        checkboxPizza: state.checkboxPizza,
        checkboxRestaurantPayment: state.checkboxRestaurantPayment,
        checkboxVegan: state.checkboxVegan,
        checkboxMotorCourier: state.checkboxMotorCourier,
        checkboxCoffe: state.checkboxCoffe,
        minValue: state.minValue,
        checkboxTakeOutPackage: state.checkboxTakeOutPackage
      ));
}
